name: icapps_generator_example
description: A project used to demo the icapps generator
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  icapps_architecture: ^2.1.1
  injectable: ^2.3.2
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  icapps_generator:
    path: ../
  injectable_generator: ^2.4.1